In [1]:
import numpy as np
import pandas as pd

from IPython.display import display

In [2]:
dataset_path = "../data/loan_data_2007_2014.csv"
df = pd.read_csv(dataset_path)

C:\Users\THINKPAD\AppData\Local\Temp\ipykernel_10528\1970791022.py:2: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dataset_path)

In [3]:
df.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(466285, 75)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  object
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  object
 10  sub_grade                    466285 non-null  object
 11  emp_title                    438697 non-null  object
 12  emp_length                   445277 non-null  object
 13  home_ownership               466285 non-null  object
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  object
 16  issue_d                      466285 non-null  object
 17  loan_status                  466285 non-null  object
 18  pymnt_plan                   466285 non-null  object
 19  url                          466285 non-null  object
 20  desc                         125981 non-null  object
 21  purpose                      466285 non-null  object
 22  title                        466264 non-null  object
 23  zip_code                     466285 non-null  object
 24  addr_state                   466285 non-null  object
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  object
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  object
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  object
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  object
 49  last_credit_pull_d           466243 non-null  object
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  object
 54  annual_inc_joint             0 non-null       float64
 55  dti_joint                    0 non-null       float64
 56  verification_status_joint    0 non-null       float64
 57  acc_now_delinq               466256 non-null  float64
 58  tot_coll_amt                 396009 non-null  float64
 59  tot_cur_bal                  396009 non-null  float64
 60  open_acc_6m                  0 non-null       float64
 61  open_il_6m                   0 non-null       float64
 62  open_il_12m                  0 non-null       float64
 63  open_il_24m                  0 non-null       float64
 64  mths_since_rcnt_il           0 non-null       float64
 65  total_bal_il                 0 non-null       float64
 66  il_util                      0 non-null       float64
 67  open_rv_12m                  0 non-null       float64
 68  open_rv_24m                  0 non-null       float64
 69  max_bal_bc                   0 non-null       float64
 70  all_util                     0 non-null       float64
 71  total_rev_hi_lim             396009 non-null  float64
 72  inq_fi                       0 non-null       float64
 73  total_cu_tl                  0 non-null       float64
 74  inq_last_12m                 0 non-null       float64
dtypes: float64(46), int64(7), object(22)
memory usage: 266.8+ MB

In [6]:
df['loan_status'].value_counts()

loan_status
Current                                                224226
Fully Paid                                             184739
Charged Off                                             42475
Late (31-120 days)                                       6900
In Grace Period                                          3146
Does not meet the credit policy. Status:Fully Paid       1988
Late (16-30 days)                                        1218
Default                                                   832
Does not meet the credit policy. Status:Charged Off       761
Name: count, dtype: int64

In [7]:
bad_statuses = [
    'Charged Off', 'Default', 'Late (31-120 days)', 
    'Late (16-30 days)', 'In Grace Period', 
    'Does not meet the credit policy. Status:Charged Off'
]

df['target'] = df['loan_status'].isin(bad_statuses).astype(int)

df.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,target
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [8]:
# Handle Kolom Nan
missing_percentage = df.isnull().mean() * 100

cols_to_drop = missing_percentage[missing_percentage > 50].index.tolist()

print(f"Jumlah kolom yang dibuang karena >50% kosong: {len(cols_to_drop)}")
print("Daftar kolom yang dibuang:", cols_to_drop)

df_clean = df.drop(columns=cols_to_drop)

print(f"Dimensi data setelah kolom kosong dibuang: {df_clean.shape}")
df_clean.head()

Jumlah kolom yang dibuang karena >50% kosong: 21
Daftar kolom yang dibuang: ['desc', 'mths_since_last_delinq', 'mths_since_last_record', 'mths_since_last_major_derog', 'annual_inc_joint', 'dti_joint', 'verification_status_joint', 'open_acc_6m', 'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'inq_fi', 'total_cu_tl', 'inq_last_12m']
Dimensi data setelah kolom kosong dibuang: (466285, 55)

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,target
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,...,NaN,Jan-16,0.0,1,INDIVIDUAL,0.0,NaN,NaN,NaN,0
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,...,NaN,Sep-13,0.0,1,INDIVIDUAL,0.0,NaN,NaN,NaN,1
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,...,NaN,Jan-16,0.0,1,INDIVIDUAL,0.0,NaN,NaN,NaN,0
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,...,NaN,Jan-15,0.0,1,INDIVIDUAL,0.0,NaN,NaN,NaN,0
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,...,Feb-16,Jan-16,0.0,1,INDIVIDUAL,0.0,NaN,NaN,NaN,0

In [9]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 55 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Unnamed: 0                  466285 non-null  int64
 1   id                          466285 non-null  int64
 2   member_id                   466285 non-null  int64
 3   loan_amnt                   466285 non-null  int64
 4   funded_amnt                 466285 non-null  int64
 5   funded_amnt_inv             466285 non-null  float64
 6   term                        466285 non-null  object
 7   int_rate                    466285 non-null  float64
 8   installment                 466285 non-null  float64
 9   grade                       466285 non-null  object
 10  sub_grade                   466285 non-null  object
 11  emp_title                   438697 non-null  object
 12  emp_length                  445277 non-null  object
 13  home_ownership              466285 non-null  object
 14  annual_inc                  466281 non-null  float64
 15  verification_status         466285 non-null  object
 16  issue_d                     466285 non-null  object
 17  loan_status                 466285 non-null  object
 18  pymnt_plan                  466285 non-null  object
 19  url                         466285 non-null  object
 20  purpose                     466285 non-null  object
 21  title                       466264 non-null  object
 22  zip_code                    466285 non-null  object
 23  addr_state                  466285 non-null  object
 24  dti                         466285 non-null  float64
 25  delinq_2yrs                 466256 non-null  float64
 26  earliest_cr_line            466256 non-null  object
 27  inq_last_6mths              466256 non-null  float64
 28  open_acc                    466256 non-null  float64
 29  pub_rec                     466256 non-null  float64
 30  revol_bal                   466285 non-null  int64
 31  revol_util                  465945 non-null  float64
 32  total_acc                   466256 non-null  float64
 33  initial_list_status         466285 non-null  object
 34  out_prncp                   466285 non-null  float64
 35  out_prncp_inv               466285 non-null  float64
 36  total_pymnt                 466285 non-null  float64
 37  total_pymnt_inv             466285 non-null  float64
 38  total_rec_prncp             466285 non-null  float64
 39  total_rec_int               466285 non-null  float64
 40  total_rec_late_fee          466285 non-null  float64
 41  recoveries                  466285 non-null  float64
 42  collection_recovery_fee     466285 non-null  float64
 43  last_pymnt_d                465909 non-null  object
 44  last_pymnt_amnt             466285 non-null  float64
 45  next_pymnt_d                239071 non-null  object
 46  last_credit_pull_d          466243 non-null  object
 47  collections_12_mths_ex_med  466140 non-null  float64
 48  policy_code                 466285 non-null  int64
 49  application_type            466285 non-null  object
 50  acc_now_delinq              466256 non-null  float64
 51  tot_coll_amt                396009 non-null  float64
 52  tot_cur_bal                 396009 non-null  float64
 53  total_rev_hi_lim            396009 non-null  float64
 54  target                      466285 non-null  int32
dtypes: float64(26), int32(1), int64(7), object(21)
memory usage: 193.9+ MB

In [10]:
irrelevant_columns = ['Unnamed: 0', 'id', 'member_id', 'url', 'emp_title', 'title',
                      'issue_d', 'total_pymnt', 'recoveries', 'collection_recovery_fee', 'last_pymnt_amnt',
                      'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
                      'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d',
                      'out_prncp', 'out_prncp_inv',
                      'zip_code', 'addr_state',
                      'loan_status']

df_clean = df_clean.drop(columns=irrelevant_columns)

nunique_colums = [col for col in df_clean.columns if df[col].nunique() == 1]

print(f"Kolom zero variance : {nunique_colums}")
display(df_clean[nunique_colums].value_counts())

df_clean = df_clean.drop(columns=nunique_colums)

df_clean.info()

Kolom zero variance : ['policy_code', 'application_type']

policy_code  application_type
1            INDIVIDUAL          466285
Name: count, dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 30 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   loan_amnt                   466285 non-null  int64
 1   funded_amnt                 466285 non-null  int64
 2   funded_amnt_inv             466285 non-null  float64
 3   term                        466285 non-null  object
 4   int_rate                    466285 non-null  float64
 5   installment                 466285 non-null  float64
 6   grade                       466285 non-null  object
 7   sub_grade                   466285 non-null  object
 8   emp_length                  445277 non-null  object
 9   home_ownership              466285 non-null  object
 10  annual_inc                  466281 non-null  float64
 11  verification_status         466285 non-null  object
 12  pymnt_plan                  466285 non-null  object
 13  purpose                     466285 non-null  object
 14  dti                         466285 non-null  float64
 15  delinq_2yrs                 466256 non-null  float64
 16  earliest_cr_line            466256 non-null  object
 17  inq_last_6mths              466256 non-null  float64
 18  open_acc                    466256 non-null  float64
 19  pub_rec                     466256 non-null  float64
 20  revol_bal                   466285 non-null  int64
 21  revol_util                  465945 non-null  float64
 22  total_acc                   466256 non-null  float64
 23  initial_list_status         466285 non-null  object
 24  collections_12_mths_ex_med  466140 non-null  float64
 25  acc_now_delinq              466256 non-null  float64
 26  tot_coll_amt                396009 non-null  float64
 27  tot_cur_bal                 396009 non-null  float64
 28  total_rev_hi_lim            396009 non-null  float64
 29  target                      466285 non-null  int32
dtypes: float64(16), int32(1), int64(3), object(10)
memory usage: 104.9+ MB

In [11]:
df_clean['pymnt_plan'].value_counts()

pymnt_plan
n    466276
y         9
Name: count, dtype: int64

In [12]:
df_clean = df_clean = df_clean.drop(columns='pymnt_plan')
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 29 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   loan_amnt                   466285 non-null  int64
 1   funded_amnt                 466285 non-null  int64
 2   funded_amnt_inv             466285 non-null  float64
 3   term                        466285 non-null  object
 4   int_rate                    466285 non-null  float64
 5   installment                 466285 non-null  float64
 6   grade                       466285 non-null  object
 7   sub_grade                   466285 non-null  object
 8   emp_length                  445277 non-null  object
 9   home_ownership              466285 non-null  object
 10  annual_inc                  466281 non-null  float64
 11  verification_status         466285 non-null  object
 12  purpose                     466285 non-null  object
 13  dti                         466285 non-null  float64
 14  delinq_2yrs                 466256 non-null  float64
 15  earliest_cr_line            466256 non-null  object
 16  inq_last_6mths              466256 non-null  float64
 17  open_acc                    466256 non-null  float64
 18  pub_rec                     466256 non-null  float64
 19  revol_bal                   466285 non-null  int64
 20  revol_util                  465945 non-null  float64
 21  total_acc                   466256 non-null  float64
 22  initial_list_status         466285 non-null  object
 23  collections_12_mths_ex_med  466140 non-null  float64
 24  acc_now_delinq              466256 non-null  float64
 25  tot_coll_amt                396009 non-null  float64
 26  tot_cur_bal                 396009 non-null  float64
 27  total_rev_hi_lim            396009 non-null  float64
 28  target                      466285 non-null  int32
dtypes: float64(16), int32(1), int64(3), object(9)
memory usage: 101.4+ MB

In [13]:
df_clean['grade'].value_counts()

grade
B    136929
C    125293
D     76888
A     74867
E     35757
F     13229
G      3322
Name: count, dtype: int64

In [14]:
df_clean['sub_grade'].value_counts()

sub_grade
B3    31686
B4    30505
C1    26953
C2    26740
B2    26610
C3    25317
B5    25252
C4    24105
B1    22876
C5    22178
A5    21757
D1    19261
A4    19045
D2    17046
D3    14916
D4    14099
A3    12568
D5    11566
A2    10956
A1    10541
E1     9033
E2     8669
E3     6976
E4     5992
E5     5087
F1     3940
F2     3001
F3     2708
F4     2067
F5     1513
G1     1109
G2      823
G3      583
G4      422
G5      385
Name: count, dtype: int64

In [15]:
df_clean = df_clean.drop(columns='grade')
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   loan_amnt                   466285 non-null  int64
 1   funded_amnt                 466285 non-null  int64
 2   funded_amnt_inv             466285 non-null  float64
 3   term                        466285 non-null  object
 4   int_rate                    466285 non-null  float64
 5   installment                 466285 non-null  float64
 6   sub_grade                   466285 non-null  object
 7   emp_length                  445277 non-null  object
 8   home_ownership              466285 non-null  object
 9   annual_inc                  466281 non-null  float64
 10  verification_status         466285 non-null  object
 11  purpose                     466285 non-null  object
 12  dti                         466285 non-null  float64
 13  delinq_2yrs                 466256 non-null  float64
 14  earliest_cr_line            466256 non-null  object
 15  inq_last_6mths              466256 non-null  float64
 16  open_acc                    466256 non-null  float64
 17  pub_rec                     466256 non-null  float64
 18  revol_bal                   466285 non-null  int64
 19  revol_util                  465945 non-null  float64
 20  total_acc                   466256 non-null  float64
 21  initial_list_status         466285 non-null  object
 22  collections_12_mths_ex_med  466140 non-null  float64
 23  acc_now_delinq              466256 non-null  float64
 24  tot_coll_amt                396009 non-null  float64
 25  tot_cur_bal                 396009 non-null  float64
 26  total_rev_hi_lim            396009 non-null  float64
 27  target                      466285 non-null  int32
dtypes: float64(16), int32(1), int64(3), object(8)
memory usage: 97.8+ MB

In [16]:
df_clean['earliest_cr_line'].value_counts()

earliest_cr_line
Oct-00    3674
Aug-00    3597
Aug-01    3455
Oct-99    3406
Oct-01    3329
          ...
Jul-55       1
Feb-57       1
Oct-54       1
May-53       1
Nov-56       1
Name: count, Length: 664, dtype: int64

In [17]:
split_date = df_clean['earliest_cr_line'].str.split('-', expand=True)
months_str = split_date[0]
years_short = split_date[1].astype('Int64')

years_full = (2000 + years_short).mask(years_short > 26, 1900 + years_short)

month_map = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6, 
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
}
month_nums = months_str.map(month_map).astype('Int64')

df_clean['mths_since_earliest_cr_line'] = (2026 - years_full) * 12 + (6 - month_nums)

df_clean = df_clean.drop(columns='earliest_cr_line')
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 28 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    466285 non-null  int64
 1   funded_amnt                  466285 non-null  int64
 2   funded_amnt_inv              466285 non-null  float64
 3   term                         466285 non-null  object
 4   int_rate                     466285 non-null  float64
 5   installment                  466285 non-null  float64
 6   sub_grade                    466285 non-null  object
 7   emp_length                   445277 non-null  object
 8   home_ownership               466285 non-null  object
 9   annual_inc                   466281 non-null  float64
 10  verification_status          466285 non-null  object
 11  purpose                      466285 non-null  object
 12  dti                          466285 non-null  float64
 13  delinq_2yrs                  466256 non-null  float64
 14  inq_last_6mths               466256 non-null  float64
 15  open_acc                     466256 non-null  float64
 16  pub_rec                      466256 non-null  float64
 17  revol_bal                    466285 non-null  int64
 18  revol_util                   465945 non-null  float64
 19  total_acc                    466256 non-null  float64
 20  initial_list_status          466285 non-null  object
 21  collections_12_mths_ex_med   466140 non-null  float64
 22  acc_now_delinq               466256 non-null  float64
 23  tot_coll_amt                 396009 non-null  float64
 24  tot_cur_bal                  396009 non-null  float64
 25  total_rev_hi_lim             396009 non-null  float64
 26  target                       466285 non-null  int32
 27  mths_since_earliest_cr_line  466256 non-null  Int64
dtypes: Int64(1), float64(16), int32(1), int64(3), object(7)
memory usage: 98.3+ MB

In [18]:
df_clean['mths_since_earliest_cr_line'].head()

0    497
1    326
2    295
3    364
4    365
Name: mths_since_earliest_cr_line, dtype: Int64

## Cleaning NaN Rows

In [19]:
df_clean.isna().sum()

loan_amnt                          0
funded_amnt                        0
funded_amnt_inv                    0
term                               0
int_rate                           0
installment                        0
sub_grade                          0
emp_length                     21008
home_ownership                     0
annual_inc                         4
verification_status                0
purpose                            0
dti                                0
delinq_2yrs                       29
inq_last_6mths                    29
open_acc                          29
pub_rec                           29
revol_bal                          0
revol_util                       340
total_acc                         29
initial_list_status                0
collections_12_mths_ex_med       145
acc_now_delinq                    29
tot_coll_amt                   70276
tot_cur_bal                    70276
total_rev_hi_lim               70276
target                             0
mths_since_earliest_cr_line       29
dtype: int64

In [20]:
nan_ratio = df_clean.isna().mean()

cols_low_nan = nan_ratio[(nan_ratio > 0) & (nan_ratio < 0.01)].index

display(cols_low_nan)

df_clean = df_clean.dropna(subset=cols_low_nan)
df_clean.info()

Index(['annual_inc', 'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec',
       'revol_util', 'total_acc', 'collections_12_mths_ex_med',
       'acc_now_delinq', 'mths_since_earliest_cr_line'],
      dtype='object')

<class 'pandas.core.frame.DataFrame'>
Index: 465832 entries, 0 to 466284
Data columns (total 28 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    465832 non-null  int64
 1   funded_amnt                  465832 non-null  int64
 2   funded_amnt_inv              465832 non-null  float64
 3   term                         465832 non-null  object
 4   int_rate                     465832 non-null  float64
 5   installment                  465832 non-null  float64
 6   sub_grade                    465832 non-null  object
 7   emp_length                   444836 non-null  object
 8   home_ownership               465832 non-null  object
 9   annual_inc                   465832 non-null  float64
 10  verification_status          465832 non-null  object
 11  purpose                      465832 non-null  object
 12  dti                          465832 non-null  float64
 13  delinq_2yrs                  465832 non-null  float64
 14  inq_last_6mths               465832 non-null  float64
 15  open_acc                     465832 non-null  float64
 16  pub_rec                      465832 non-null  float64
 17  revol_bal                    465832 non-null  int64
 18  revol_util                   465832 non-null  float64
 19  total_acc                    465832 non-null  float64
 20  initial_list_status          465832 non-null  object
 21  collections_12_mths_ex_med   465832 non-null  float64
 22  acc_now_delinq               465832 non-null  float64
 23  tot_coll_amt                 395790 non-null  float64
 24  tot_cur_bal                  395790 non-null  float64
 25  total_rev_hi_lim             395790 non-null  float64
 26  target                       465832 non-null  int32
 27  mths_since_earliest_cr_line  465832 non-null  Int64
dtypes: Int64(1), float64(16), int32(1), int64(3), object(7)
memory usage: 101.7+ MB

In [21]:
df_clean.isna().sum()

loan_amnt                          0
funded_amnt                        0
funded_amnt_inv                    0
term                               0
int_rate                           0
installment                        0
sub_grade                          0
emp_length                     20996
home_ownership                     0
annual_inc                         0
verification_status                0
purpose                            0
dti                                0
delinq_2yrs                        0
inq_last_6mths                     0
open_acc                           0
pub_rec                            0
revol_bal                          0
revol_util                         0
total_acc                          0
initial_list_status                0
collections_12_mths_ex_med         0
acc_now_delinq                     0
tot_coll_amt                   70042
tot_cur_bal                    70042
total_rev_hi_lim               70042
target                             0
mths_since_earliest_cr_line        0
dtype: int64

In [22]:
df_clean['emp_length'].value_counts()

emp_length
10+ years    149943
2 years       41333
3 years       36564
< 1 year      36176
5 years       30753
1 year        29570
4 years       27996
7 years       26157
6 years       26091
8 years       22379
9 years       17874
Name: count, dtype: int64

In [23]:
df_clean['emp_length'] = df_clean['emp_length'].fillna(-1)

emp_length_map = {
    -1: -1,
    '< 1 year': 0,
    '2 years': 2,
    '3 years': 3,
    '5 years': 5,
    '1 year': 1,
    '4 years': 4,
    '7 years': 7,
    '6 years': 6,
    '8 years': 8,
    '9 years': 9,
    '10+ years': 10,
}

df_clean['emp_length'] = df_clean['emp_length'].map(emp_length_map).astype('int32')

df_clean['emp_length'].value_counts()

emp_length
 10    149943
 2      41333
 3      36564
 0      36176
 5      30753
 1      29570
 4      27996
 7      26157
 6      26091
 8      22379
-1      20996
 9      17874
Name: count, dtype: int64

In [24]:
df_clean['tot_coll_amt'] = df_clean['tot_coll_amt'].fillna(0)

df_clean['tot_cur_bal'] = df_clean['tot_cur_bal'].fillna(df_clean['tot_cur_bal'].median())
df_clean['total_rev_hi_lim'] = df_clean['total_rev_hi_lim'].fillna(df_clean['total_rev_hi_lim'].median())

In [25]:
df_clean[['loan_amnt', 'funded_amnt', 'revol_bal', 'mths_since_earliest_cr_line']].head()

   loan_amnt  funded_amnt  revol_bal  mths_since_earliest_cr_line
0       5000         5000      13648                          497
1       2500         2500       1687                          326
2       2400         2400       2956                          295
3      10000        10000       5598                          364
4       3000         3000      27783                          365

In [26]:
with pd.option_context('display.max_columns', None):
    display(df_clean.head())

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,sub_grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,collections_12_mths_ex_med,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,target,mths_since_earliest_cr_line
0,5000,5000,4975.0,36 months,10.65,162.87,B2,10,RENT,24000.0,Verified,credit_card,27.65,0.0,1.0,3.0,0.0,13648,83.7,9.0,f,0.0,0.0,0.0,81518.5,22900.0,0,497
1,2500,2500,2500.0,60 months,15.27,59.83,C4,0,RENT,30000.0,Source Verified,car,1.00,0.0,5.0,3.0,0.0,1687,9.4,4.0,f,0.0,0.0,0.0,81518.5,22900.0,1,326
2,2400,2400,2400.0,36 months,15.96,84.33,C5,10,RENT,12252.0,Not Verified,small_business,8.72,0.0,2.0,2.0,0.0,2956,98.5,10.0,f,0.0,0.0,0.0,81518.5,22900.0,0,295
3,10000,10000,10000.0,36 months,13.49,339.31,C1,10,RENT,49200.0,Source Verified,other,20.00,0.0,1.0,10.0,0.0,5598,21.0,37.0,f,0.0,0.0,0.0,81518.5,22900.0,0,364
4,3000,3000,3000.0,60 months,12.69,67.79,B5,1,RENT,80000.0,Source Verified,other,17.94,0.0,0.0,15.0,0.0,27783,53.9,38.0,f,0.0,0.0,0.0,81518.5,22900.0,0,365

In [27]:
int_cols = df_clean.select_dtypes(include=['int64', 'Int64', 'int32']).columns

df_clean[int_cols] = df_clean[int_cols].astype('int32')

In [28]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 465832 entries, 0 to 466284
Data columns (total 28 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    465832 non-null  int32
 1   funded_amnt                  465832 non-null  int32
 2   funded_amnt_inv              465832 non-null  float64
 3   term                         465832 non-null  object
 4   int_rate                     465832 non-null  float64
 5   installment                  465832 non-null  float64
 6   sub_grade                    465832 non-null  object
 7   emp_length                   465832 non-null  int32
 8   home_ownership               465832 non-null  object
 9   annual_inc                   465832 non-null  float64
 10  verification_status          465832 non-null  object
 11  purpose                      465832 non-null  object
 12  dti                          465832 non-null  float64
 13  delinq_2yrs                  465832 non-null  float64
 14  inq_last_6mths               465832 non-null  float64
 15  open_acc                     465832 non-null  float64
 16  pub_rec                      465832 non-null  float64
 17  revol_bal                    465832 non-null  int32
 18  revol_util                   465832 non-null  float64
 19  total_acc                    465832 non-null  float64
 20  initial_list_status          465832 non-null  object
 21  collections_12_mths_ex_med   465832 non-null  float64
 22  acc_now_delinq               465832 non-null  float64
 23  tot_coll_amt                 465832 non-null  float64
 24  tot_cur_bal                  465832 non-null  float64
 25  total_rev_hi_lim             465832 non-null  float64
 26  target                       465832 non-null  int32
 27  mths_since_earliest_cr_line  465832 non-null  int32
dtypes: float64(16), int32(6), object(6)
memory usage: 92.4+ MB

In [29]:
df_clean.to_csv('../data/cleaned_data.csv', index=False)